Add Beamswap Proposal
moonbeam-foundation/grants pull request #7
Opened 2023-04-06 14:44 UTC by devjanj

2023-04-06 19:55 UTC, sicco-moonbeam requested changes

2023-04-06 19:55 UTC, sicco-moonbeam commented on revised/beamswap-proposal.md
> +![|602x339](upload://fD6fkHq6wKjwisKaZZgPQIGbwJM.jpeg)
Can you also upload the images to the revised/assets/beamswap folder? Otherwise we'll end up with some empty placeholders.

2023-04-06 19:55 UTC, sicco-moonbeam commented on revised/beamswap-proposal.md
> +## ![|602x336](upload://75F6DG9Az6RDbb3OX8cSCJpjsPs.jpeg)
Can you also upload the images to the revised/assets/beamswap folder? Otherwise we'll end up with some empty placeholders.

2023-04-06 19:55 UTC, sicco-moonbeam commented on revised/beamswap-proposal.md
> +![|602x339](upload://1FHnZ0saMSo0aa6sui7p9KCd5Br.jpeg)
Can you also upload the images to the revised/assets/beamswap folder? Otherwise we'll end up with some empty placeholders.

2023-04-06 19:55 UTC, sicco-moonbeam commented on revised/beamswap-proposal.md
> +![|602x339](upload://6XeJKGFJn4mRwuNFnLmUsrTPR7E.jpeg)
Can you also upload the images to the revised/assets/beamswap folder? Otherwise we'll end up with some empty placeholders.

2023-04-06 19:55 UTC, sicco-moonbeam commented on revised/beamswap-proposal.md
> +![|602x339](upload://2fsk4Ns2dkTo8tvs0OZnF98lbA7.jpeg)
Can you also upload the images to the revised/assets/beamswap folder? Otherwise we'll end up with some empty placeholders.

2023-04-06 19:55 UTC, sicco-moonbeam commented on revised/beamswap-proposal.md
> +![|602x339](upload://stGnLWpgEEQMwhCLHXfGMDckMSP.jpeg)
Can you also upload the images to the revised/assets/beamswap folder? Otherwise we'll end up with some empty placeholders.

2023-04-06 19:55 UTC, sicco-moonbeam commented on revised/beamswap-proposal.md
> +![|602x339](upload://4UU32xt3zIprYMzEIq4fgiebraE.jpeg)
Can you also upload the images to the revised/assets/beamswap folder? Otherwise we'll end up with some empty placeholders.

2023-04-06 19:55 UTC, sicco-moonbeam commented on revised/beamswap-proposal.md
> +![|602x339](upload://jah9xRmlIOoddRGwE5EnuJ09hdO.jpeg)
Can you also upload the images to the revised/assets/beamswap folder? Otherwise we'll end up with some empty placeholders.

2023-04-06 19:55 UTC, sicco-moonbeam commented on revised/beamswap-proposal.md
> +![|602x339](upload://91jHDEqQmYsNh2v469wzV5IF4Ac.jpeg)
Can you also upload the images to the revised/assets/beamswap folder? Otherwise we'll end up with some empty placeholders.

2023-04-06 19:55 UTC, sicco-moonbeam commented on revised/beamswap-proposal.md
> +![|602x339](upload://3toEfKHojF1afpZQrjK0LvBFEQG.jpeg)
Can you also upload the images to the revised/assets/beamswap folder? Otherwise we'll end up with some empty placeholders.

2023-04-07 12:07 UTC, devjanj commented
Added Images for Beamswap Proposal

2023-04-07 16:05 UTC, sicco-moonbeam approved these changes

2023-04-07 16:05 UTC, merged